refactor: `react-select` -> `mui-select` 및 `Provider` 수정
wtb-kr/wtb-web pull request #24
Opened 2023-08-02 16:18 UTC by jlee0425

## 해결하려는 문제가 무엇인가요?
- 컴포넌트 대체
- `Select` 선택된 벨류와 url과 연동되게 수정
- mui/material이 tailwindcss를 override하는 부분 수정

## 어떻게 해결했나요?
- `react-select` -> `mui/select`
- url정보를 기준으로 `Select` value prop에 전달
- `Provider` 수정

## 참고 자료

https://github.com/wtb-kr/wtb-web/assets/40153724/e85b0674-5863-40fb-96a8-9dc12cc9c6ff

2023-08-02 16:19 UTC, jlee0425 commented
![](https://github.trello.services/images/mini-trello-icon.png) [material-tailwind -> MUI Migration](https://trello.com/c/dgg5pJGS/41-material-tailwind-mui-migration)

2023-08-02 16:47 UTC, edenist-x-x reviewed
수고하셨습니다 !

2023-08-02 18:45 UTC, keypport requested changes
롤백 요청

dev-log [FE 전역상태관리]를 확인해 주세요
url과 연동할 경우, 카테고리 변경시 type 값이 유지되지 않는 문제가 있어 전역상태관리를 유지하기로 했었어요

현재 코드에는 카테고리 변경시 error가 발생하는 문제가 있고
root에서의 redirects destination도 변경해야 하지만
전역상태로 복구한다면 둘 다 해결될 문제에요

[이전 PR](https://github.com/wtb-kr/wtb-web/pull/23)에서 cols === 1 을 true로 둔 부분을 설명해 주세요

2023-08-02 21:12 UTC, keypport commented
`그럼 해당 값이 URL에 포함되지 않은 경우의 디폴트값을 정해두고, URL과 전역으로 두개를 들고 있어야 할거 같아요
최선은 URL만으로 관리하는 건데 키폿님 말씀의 경우라면 전역상태관리 툴을 사용해야겠네요`

저는 나중에 말씀하신 전역 상태 툴만 사용하겠다는 것으로 이해했었는데
url query string과 전역 상태를 둘 다 쓴다는 것은 어떤 의미인가요?
같은 값을 두 가지 형태로 갖는다면 중복 아닌가요?

categories-navbar와 type-selector를 독립적으로 쓰기 위해서는
type을 전역 상태로 관리할 필요가 있어요

발생한 문제들을 고려하면 전역 상태로 관리하던 type을 query string으로 전환할 이유가 없어 보여요

2023-08-03 00:04 UTC, jlee0425 commented
> 롤백 요청
> 
> dev-log [FE 전역상태관리]를 확인해 주세요 url과 연동할 경우, 카테고리 변경시 type 값이 유지되지 않는 문제가 있어 전역상태관리를 유지하기로 했었어요
> 
> 현재 코드에는 카테고리 변경시 error가 발생하는 문제가 있고

1. 현재 카테고리 변경시의 에러핸들링을 넣지 않아서 에러가 발생했네요.
   -> 아래에 키폿님이 말씀하신 거 처럼 그냥 전역관리로 전체전환 하면 해결됩니다.

> [이전 PR](https://github.com/wtb-kr/wtb-web/pull/23)에서 cols === 1 을 true로 둔 부분을 설명해 주세요

2. 현재 `migration`자체가 진행중인 단계로, 해당 부분은 `zustand`가 들어가면서 해결되는 부분입니다.
현재 진행한 부분은 `layout`관련된 내용으로, 전역상태관리까지 포함될 경우 PR의 양이 너무 많아져서 일단 보류했습니다.

>  root에서의 redirects destination도 변경해야 하지만 전역상태로 복구한다면 둘 다 해결될 문제에요

3. root 에서의 redirects 부분은 뎁스를 많이 가져간 이상 피해갈 수 없는 부분이라고 생각합니다. "g", "categories"와 같이 프론트에서 사용되는 로직과 관계없는 부분은 사라져도 된다고 생각합니다. `about`등 1뎁스에 다른 페이지가 추가된 경우 미들웨어 등으로 처리가 가능합니다.


### 롤백을 원하시면 롤백은 진행할게요.

2023-08-03 00:31 UTC, keypport commented
type의 전역 상태 -> query string 전환에서 생긴 문제를 해결할 수 있는 것이 아니라면
전역 상태를 쓰는 게 좋을 거 같아요

2번에서 migration의 PR 사이즈를 줄이기 위해 임시로 처리한 부분은 설명이 있었다면 좋았을 거 같아요
migration 진행 단계에서 작게 나누는 것이 중요하니 그렇게 해봐요

2023-08-06 06:42 UTC, jlee0425 commented
@keypport 
URL로 상태관리 되게 수정하였습니다. 영상 참조부탁해요

2023-08-06 06:57 UTC, keepinblazing commented
고생하셨습니다.

2023-08-06 07:48 UTC, keypport commented
수고하셨어요 !

home을 누르거나, mypage에서 돌아올 때 type이 유지되지 않는 이슈가 있지만
url에 포함될 경우 링크 공유의 장점이 있으니 바꿨을 때의 이점이 더 큰 거 같아요

그런데 현재 root에서 redirect되는 /g/키보드 에서
404 페이지가 뜨는 것은 해결하고 합쳐야 할 거 같아요

간단하게는 redirect 경로에 categories/커스텀 까지 넣어 해결하는 방법이 있지만
category는 서버에서 rank 값으로 정렬하여 전달되니, 이걸 이용해서 지정되지 않았을 때의 redirect를 처리하면 좋을 거 같아요

2023-08-06 07:49 UTC, keypport approved these changes

2023-08-06 07:59 UTC, hokikie approved these changes
👍🏻

2023-08-06 08:48 UTC, merged